-- ===== 私信系统 (DM) 2026-08-07 =====
-- 脱离房间的持久 1v1 会话。方案B: 匿名也能收发(靠在场关系发起),正式账号享持久化。
-- 结构照抄 eh_messages 的 whisper 命门(仅收发双方可见)。

-- ---- 表1: 会话线 (两人一条, user_a<user_b 规范化排序防重复建) ----
create table if not exists public.eh_dm_threads (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null,                     -- 规范化: 较小 uid
  user_b uuid not null,                     -- 规范化: 较大 uid
  last_msg_at timestamptz,                   -- 最后一条消息时间(列表排序)
  last_text text,                            -- 最后一条预览(列表展示)
  last_from uuid,                            -- 最后一条发送方(列表判断"对方发的")
  created_at timestamptz default now(),
  constraint eh_dm_threads_pair_uk unique (user_a, user_b),
  constraint eh_dm_threads_order_ck check (user_a < user_b)
);

-- ---- 表2: 会话消息 ----
create table if not exists public.eh_dm_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.eh_dm_threads(id) on delete cascade,
  from_uid uuid not null,
  text text not null,
  read_at timestamptz,                       -- 对方读到的时间(为空=未读)
  created_at timestamptz default now()
);
create index if not exists eh_dm_messages_thread_idx on public.eh_dm_messages(thread_id, created_at);

-- ---- RLS ----
alter table public.eh_dm_threads enable row level security;
alter table public.eh_dm_messages enable row level security;

-- threads: 仅会话双方可见; insert 要求自己是其中一方且规范化排序(实际统一走 RPC)
drop policy if exists dm_threads_select on public.eh_dm_threads;
create policy dm_threads_select on public.eh_dm_threads
  for select to public
  using (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists dm_threads_insert on public.eh_dm_threads;
create policy dm_threads_insert on public.eh_dm_threads
  for insert to public
  with check ((auth.uid() = user_a or auth.uid() = user_b) and user_a < user_b);

-- messages: 仅所属 thread 的双方可读; insert 要求 from_uid=自己 且是该 thread 成员
drop policy if exists dm_messages_select on public.eh_dm_messages;
create policy dm_messages_select on public.eh_dm_messages
  for select to public
  using (exists (
    select 1 from public.eh_dm_threads t
    where t.id = thread_id and (auth.uid() = t.user_a or auth.uid() = t.user_b)
  ));

drop policy if exists dm_messages_insert on public.eh_dm_messages;
create policy dm_messages_insert on public.eh_dm_messages
  for insert to public
  with check (
    from_uid = auth.uid()
    and exists (
      select 1 from public.eh_dm_threads t
      where t.id = thread_id and (auth.uid() = t.user_a or auth.uid() = t.user_b)
    )
  );

-- ---- 触发器: 发消息后自动更新 thread 的 last_* (免客户端 UPDATE 权限) ----
create or replace function public.eh_dm_touch_thread()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.eh_dm_threads
    set last_msg_at = new.created_at, last_text = new.text, last_from = new.from_uid
    where id = new.thread_id;
  return new;
end;
$$;
drop trigger if exists eh_dm_touch on public.eh_dm_messages;
create trigger eh_dm_touch after insert on public.eh_dm_messages
  for each row execute function public.eh_dm_touch_thread();

-- ---- RPC: 取或建会话线(原子, 规范化两 uid 排序, 绕开 insert 竞态) ----
create or replace function public.eh_dm_get_or_create(p_other uuid)
returns public.eh_dm_threads
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_me uuid := auth.uid();
  v_a uuid; v_b uuid;
  v_row public.eh_dm_threads%rowtype;
begin
  if v_me is null then raise exception 'not authenticated'; end if;
  if p_other is null or p_other = v_me then raise exception 'invalid target'; end if;
  -- 对方必须是真实存在的用户
  if not exists (select 1 from public.eh_users u where u.id = p_other) then
    raise exception 'target not found';
  end if;
  if v_me < p_other then v_a := v_me; v_b := p_other; else v_a := p_other; v_b := v_me; end if;
  insert into public.eh_dm_threads(user_a, user_b) values (v_a, v_b)
    on conflict (user_a, user_b) do nothing;
  select * into v_row from public.eh_dm_threads where user_a = v_a and user_b = v_b;
  return v_row;
end;
$$;
grant execute on function public.eh_dm_get_or_create(uuid) to public;

-- ---- RPC: 标记某会话线里"对方发来的消息"为已读 ----
create or replace function public.eh_dm_mark_read(p_thread uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare v_me uuid := auth.uid();
begin
  if v_me is null then raise exception 'not authenticated'; end if;
  -- 只有会话成员能标记
  if not exists (select 1 from public.eh_dm_threads t
                 where t.id = p_thread and (t.user_a = v_me or t.user_b = v_me)) then
    raise exception 'not a member';
  end if;
  update public.eh_dm_messages
    set read_at = now()
    where thread_id = p_thread and from_uid <> v_me and read_at is null;
end;
$$;
grant execute on function public.eh_dm_mark_read(uuid) to public;

-- ---- 开 Realtime replication (前端 postgres_changes 订阅新消息) ----
alter publication supabase_realtime add table public.eh_dm_messages;

-- 验证:
-- select * from public.eh_dm_get_or_create('<other-uuid>');  -- 应返回一条 thread
-- select tablename from pg_tables where tablename like 'eh_dm%';
-- 收件箱: 一次拿回所有会话线 + 对方资料 + 未读数 + 最后一条(免前端 N 次查)
create or replace function public.eh_dm_inbox()
returns table(thread_id uuid, other_uid uuid, other_name text, other_emoji text, other_color text,
              last_text text, last_msg_at timestamptz, last_from uuid, unread int)
language sql
security definer
set search_path to 'public'
as $$
  select t.id,
    case when t.user_a = auth.uid() then t.user_b else t.user_a end as other_uid,
    u.name, u.emoji, u.color,
    t.last_text, t.last_msg_at, t.last_from,
    (select count(*)::int from public.eh_dm_messages m
       where m.thread_id = t.id and m.from_uid <> auth.uid() and m.read_at is null) as unread
  from public.eh_dm_threads t
  join public.eh_users u
    on u.id = (case when t.user_a = auth.uid() then t.user_b else t.user_a end)
  where t.user_a = auth.uid() or t.user_b = auth.uid()
  order by t.last_msg_at desc nulls last
$$;
grant execute on function public.eh_dm_inbox() to public;
